[tool.poetry]
name = "keymap-drawer"
version = "0.1.0"
description = ""
authors = ["Cem Aksoylar <caksoylar@gmail.com>"]
readme = "README.md"
packages = [{include = "keymap_drawer"}]

[tool.poetry.dependencies]
python = "^3.10"
"ruamel.yaml" = "^0.17.21"
pydantic = "^1.10.2"


[tool.poetry.group.dev.dependencies]
mypy = "^0.971"
pylint = "^2.15.2"
black = "^22.8.0"
pylint-pydantic = "^0.1.4"


[tool.poetry.group.lsp]
optional = true

[tool.poetry.group.lsp.dependencies]
python-lsp-server = {extras = ["all"], version = "^1.5.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.MASTER]
extension-pkg-whitelist = "pydantic"
load-plugins = "pylint_pydantic"

[tool.pylint.'MESSAGES CONTROL']
disable = """
    too-few-public-methods,
"""

[tool.pylint.BASIC]
good-names="x,y,w,h"
